import * as Interfaces from './interfaces';

export const ISSUE_SEARCH1: Interfaces.IssueSearchResult = {
    'total_count': 2,
    'incomplete_results': false,
    'items': [
        {
            'url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/2',
            'repository_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard',
            'labels_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/2/labels{/name}',
            'comments_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/2/comments',
            'events_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/2/events',
            'html_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/2',
            'id': 395054012,
            'node_id': 'MDExOlB1bGxSZXF1ZXN0MjQxNjE2MDY5',
            'number': 2,
            'title': 'Test PR #2 - Team Mention',
            'user': {
                'login': 'chodges15',
                'id': 24880218,
                'node_id': 'MDQ6VXNlcjI0ODgwMjE4',
                'avatar_url': 'https://avatars0.githubusercontent.com/u/24880218?v=4',
                'gravatar_id': '',
                'url': 'https://api.github.com/users/chodges15',
                'html_url': 'https://github.com/chodges15',
                'followers_url': 'https://api.github.com/users/chodges15/followers',
                'following_url': 'https://api.github.com/users/chodges15/following{/other_user}',
                'gists_url': 'https://api.github.com/users/chodges15/gists{/gist_id}',
                'starred_url': 'https://api.github.com/users/chodges15/starred{/owner}{/repo}',
                'subscriptions_url': 'https://api.github.com/users/chodges15/subscriptions',
                'organizations_url': 'https://api.github.com/users/chodges15/orgs',
                'repos_url': 'https://api.github.com/users/chodges15/repos',
                'events_url': 'https://api.github.com/users/chodges15/events{/privacy}',
                'received_events_url': 'https://api.github.com/users/chodges15/received_events',
                'type': 'User',
                'site_admin': false
            },
            'labels': [],
            'state': 'open',
            'locked': false,
            'assignee': null,
            'assignees': [],
            'milestone': null,
            'comments': 1,
            'created_at': '2019-01-01T04:13:33Z',
            'updated_at': '2019-01-01T04:39:37Z',
            'closed_at': null,
            'author_association': 'MEMBER',
            'pull_request': {
                'url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/pulls/2',
                'html_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/2',
                'diff_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/2.diff',
                'patch_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/2.patch'
            },
            'body': '@LeanAgileSoftware/test ',
            'score': 1
        },
        {
            'url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/1',
            'repository_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard',
            'labels_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/1/labels{/name}',
            'comments_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/1/comments',
            'events_url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/issues/1/events',
            'html_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/1',
            'id': 395053354,
            'node_id': 'MDExOlB1bGxSZXF1ZXN0MjQxNjE1Njg0',
            'number': 1,
            'title': 'Test PR #1 - Team Mention',
            'user': {
                'login': 'chodges15',
                'id': 24880218,
                'node_id': 'MDQ6VXNlcjI0ODgwMjE4',
                'avatar_url': 'https://avatars0.githubusercontent.com/u/24880218?v=4',
                'gravatar_id': '',
                'url': 'https://api.github.com/users/chodges15',
                'html_url': 'https://github.com/chodges15',
                'followers_url': 'https://api.github.com/users/chodges15/followers',
                'following_url': 'https://api.github.com/users/chodges15/following{/other_user}',
                'gists_url': 'https://api.github.com/users/chodges15/gists{/gist_id}',
                'starred_url': 'https://api.github.com/users/chodges15/starred{/owner}{/repo}',
                'subscriptions_url': 'https://api.github.com/users/chodges15/subscriptions',
                'organizations_url': 'https://api.github.com/users/chodges15/orgs',
                'repos_url': 'https://api.github.com/users/chodges15/repos',
                'events_url': 'https://api.github.com/users/chodges15/events{/privacy}',
                'received_events_url': 'https://api.github.com/users/chodges15/received_events',
                'type': 'User',
                'site_admin': false
            },
            'labels': [],
            'state': 'open',
            'locked': false,
            'assignee': null,
            'assignees': [],
            'milestone': null,
            'comments': 0,
            'created_at': '2019-01-01T03:53:00Z',
            'updated_at': '2019-01-01T03:53:00Z',
            'closed_at': null,
            'author_association': 'MEMBER',
            'pull_request': {
                'url': 'https://api.github.com/repos/LeanAgileSoftware/lean-agile-flow-dashboard/pulls/1',
                'html_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/1',
                'diff_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/1.diff',
                'patch_url': 'https://github.com/LeanAgileSoftware/lean-agile-flow-dashboard/pull/1.patch'
            },
            'body': '@LeanAgileSoftware/test ',
            'score': 1
        }
    ]
};

export const ISSUE_SEARCH2 = {
    "total_count": 25,
    "incomplete_results": false,
    "items": [
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/99",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/99/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/99/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/99/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/99",
            "id": 576260071,
            "node_id": "MDExOlB1bGxSZXF1ZXN0Mzg0MjgwOTk1",
            "number": 99,
            "title": "Update unit tests for pull request table",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [

            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 0,
            "created_at": "2020-03-05T13:38:14Z",
            "updated_at": "2020-03-05T13:45:19Z",
            "closed_at": "2020-03-05T13:45:12Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/99",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/99",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/99.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/99.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/95",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/95/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/95/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/95/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/95",
            "id": 575112685,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzgzMzE5NTY1",
            "number": 95,
            "title": "Update release branch and branches for circle",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2020-03-04T03:30:56Z",
            "updated_at": "2020-03-04T03:40:04Z",
            "closed_at": "2020-03-04T03:34:34Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/95",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/95",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/95.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/95.patch"
            },
            "body": "See https://github.com/bahmutov/condition-circle/issues/22 for more info",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/94",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/94/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/94/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/94/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/94",
            "id": 575108516,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzgzMzE2MTIy",
            "number": 94,
            "title": "Update test dependencies",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 2,
            "created_at": "2020-03-04T03:17:05Z",
            "updated_at": "2020-03-04T03:40:02Z",
            "closed_at": "2020-03-04T03:22:00Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/94",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/94",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/94.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/94.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/92",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/92/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/92/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/92/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/92",
            "id": 575104762,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzgzMzEzMjAz",
            "number": 92,
            "title": "Timepipe",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2020-03-04T03:04:45Z",
            "updated_at": "2020-03-04T03:39:55Z",
            "closed_at": "2020-03-04T03:07:28Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/92",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/92",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/92.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/92.patch"
            },
            "body": "Puts back a time ago pipe that is compatible with newer angular and passes the linter",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/90",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/90/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/90/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/90/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/90",
            "id": 575088080,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzgzMjk5NjAy",
            "number": 90,
            "title": "Angular9 update",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 2,
            "created_at": "2020-03-04T02:18:32Z",
            "updated_at": "2020-03-04T03:40:19Z",
            "closed_at": "2020-03-04T02:22:33Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/90",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/90",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/90.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/90.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/89",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/89/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/89/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/89/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/89",
            "id": 575045474,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzgzMjY0NDg2",
            "number": 89,
            "title": "test: fix broken test",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2020-03-04T00:23:09Z",
            "updated_at": "2020-03-04T03:40:13Z",
            "closed_at": "2020-03-04T01:35:29Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/89",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/89",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/89.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/89.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/88",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/88/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/88/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/88/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/88",
            "id": 574402814,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzgyNzMyOTUz",
            "number": 88,
            "title": "Work towards green test for pull request table",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2020-03-03T04:10:26Z",
            "updated_at": "2020-03-04T03:40:22Z",
            "closed_at": "2020-03-03T04:12:14Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/88",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/88",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/88.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/88.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/75",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/75/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/75/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/75/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/75",
            "id": 567310312,
            "node_id": "MDExOlB1bGxSZXF1ZXN0Mzc2OTU5MjY2",
            "number": 75,
            "title": "Filter table for only open PRs",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2020-02-19T04:36:51Z",
            "updated_at": "2020-03-04T03:40:43Z",
            "closed_at": "2020-02-19T04:42:33Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/75",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/75",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/75.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/75.patch"
            },
            "body": "Hardcoded filter for now that restricts the table to open PRs.",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/74",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/74/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/74/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/74/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/74",
            "id": 567304544,
            "node_id": "MDExOlB1bGxSZXF1ZXN0Mzc2OTU0NTUy",
            "number": 74,
            "title": "Put back existing PR limits on renovate.json",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 2,
            "created_at": "2020-02-19T04:16:17Z",
            "updated_at": "2020-03-04T03:40:40Z",
            "closed_at": "2020-02-19T04:37:05Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/74",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/74",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/74.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/74.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/73",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/73/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/73/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/73/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/73",
            "id": 567303169,
            "node_id": "MDExOlB1bGxSZXF1ZXN0Mzc2OTUzMzg4",
            "number": 73,
            "title": "Fix error in renovate.json",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2020-02-19T04:11:45Z",
            "updated_at": "2020-03-04T03:40:46Z",
            "closed_at": "2020-02-19T04:14:35Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/73",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/73",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/73.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/73.patch"
            },
            "body": "Missed a comma",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/71",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/71/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/71/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/71/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/71",
            "id": 567287367,
            "node_id": "MDExOlB1bGxSZXF1ZXN0Mzc2OTQwODEw",
            "number": 71,
            "title": "Auto-merge enabled / renovate.json updated based on config:base ",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 2,
            "created_at": "2020-02-19T03:13:28Z",
            "updated_at": "2020-03-04T03:40:37Z",
            "closed_at": "2020-02-19T03:41:52Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/71",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/71",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/71.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/71.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/68",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/68/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/68/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/68/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/68",
            "id": 567282411,
            "node_id": "MDExOlB1bGxSZXF1ZXN0Mzc2OTM2OTky",
            "number": 68,
            "title": "Enable renovate auto-merge",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2020-02-19T02:56:45Z",
            "updated_at": "2020-02-19T03:10:22Z",
            "closed_at": "2020-02-19T03:00:36Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/68",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/68",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/68.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/68.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/64",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/64/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/64/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/64/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/64",
            "id": 567261241,
            "node_id": "MDExOlB1bGxSZXF1ZXN0Mzc2OTIwMjEw",
            "number": 64,
            "title": "Switch to Time Ago pipe",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 2,
            "created_at": "2020-02-19T01:39:08Z",
            "updated_at": "2020-02-19T02:10:42Z",
            "closed_at": "2020-02-19T01:45:38Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/64",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/64",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/64.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/64.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/48",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/48/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/48/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/48/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/48",
            "id": 512912067,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzMyODE5Mzg0",
            "number": 48,
            "title": "Angular upgrade",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 2,
            "created_at": "2019-10-27T02:51:14Z",
            "updated_at": "2019-10-27T04:17:39Z",
            "closed_at": "2019-10-27T02:53:11Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/48",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/48",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/48.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/48.patch"
            },
            "body": "Updates app to use Angular 8.",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/47",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/47/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/47/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/47/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/47",
            "id": 512911961,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzMyODE5MzE2",
            "number": 47,
            "title": "Upgrade to Angular 8",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [

            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 0,
            "created_at": "2019-10-27T02:49:26Z",
            "updated_at": "2019-10-27T02:53:41Z",
            "closed_at": "2019-10-27T02:49:45Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/47",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/47",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/47.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/47.patch"
            },
            "body": "chore(deps): update semantic-release monorepo (#23)\r\n\r\nUpgrade\r\n\r\nTemp remote angular/cdk\r\n\r\nUpdate 2\r\n\r\nUpdate to Angular 8",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/tech256/noaltech/issues/5",
            "repository_url": "https://api.github.com/repos/tech256/noaltech",
            "labels_url": "https://api.github.com/repos/tech256/noaltech/issues/5/labels{/name}",
            "comments_url": "https://api.github.com/repos/tech256/noaltech/issues/5/comments",
            "events_url": "https://api.github.com/repos/tech256/noaltech/issues/5/events",
            "html_url": "https://github.com/tech256/noaltech/pull/5",
            "id": 510372625,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzMwNzU5Mzg5",
            "number": 5,
            "title": "Add Docker Huntsville meetup",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [

            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 0,
            "created_at": "2019-10-22T00:49:44Z",
            "updated_at": "2019-10-22T03:19:59Z",
            "closed_at": "2019-10-22T03:19:59Z",
            "author_association": "CONTRIBUTOR",
            "pull_request": {
                "url": "https://api.github.com/repos/tech256/noaltech/pulls/5",
                "html_url": "https://github.com/tech256/noaltech/pull/5",
                "diff_url": "https://github.com/tech256/noaltech/pull/5.diff",
                "patch_url": "https://github.com/tech256/noaltech/pull/5.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/41",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/41/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/41/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/41/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/41",
            "id": 489447017,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzE0MjYzNzU0",
            "number": 41,
            "title": "Update package.json for renovate automerge",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 3,
            "created_at": "2019-09-04T23:12:01Z",
            "updated_at": "2019-09-19T22:24:01Z",
            "closed_at": "2019-09-11T04:03:02Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/41",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/41",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/41.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/41.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/36",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/36/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/36/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/36/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/36",
            "id": 488902303,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzEzODI4ODUw",
            "number": 36,
            "title": "update node",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 2,
            "created_at": "2019-09-04T02:08:29Z",
            "updated_at": "2019-09-19T22:24:19Z",
            "closed_at": "2019-09-04T02:11:54Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/36",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/36",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/36.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/36.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/7",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/7/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/7/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/7/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/7",
            "id": 488336155,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzEzMzc5ODI1",
            "number": 7,
            "title": "Add Local Storage for Settings",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2019-09-02T23:23:57Z",
            "updated_at": "2019-09-03T02:19:42Z",
            "closed_at": "2019-09-02T23:45:17Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/7",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/7",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/7.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/7.patch"
            },
            "body": "",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/6",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/6/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/6/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/6/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/6",
            "id": 477683479,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MzA0OTYxMDY2",
            "number": 6,
            "title": "Pull request view",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2019-08-07T03:09:34Z",
            "updated_at": "2019-09-03T02:19:39Z",
            "closed_at": "2019-08-07T03:09:48Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/6",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/6",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/6.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/6.patch"
            },
            "body": "Steps towards making an Open PR dashboard.",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/4",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/4/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/4/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/4/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/4",
            "id": 428535820,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MjY2ODcyMjE1",
            "number": 4,
            "title": "Minor updates",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2019-04-03T02:38:08Z",
            "updated_at": "2019-04-03T02:40:33Z",
            "closed_at": "2019-04-03T02:38:18Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/4",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/4",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/4.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/4.patch"
            },
            "body": "Slow changes towards getting initial settings in place to have what's needed to get pull requests from Github.",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/3",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/3/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/3/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/3/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/3",
            "id": 414811592,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MjU2NDQwNDcw",
            "number": 3,
            "title": "Just getting started",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1250207287,
                    "node_id": "MDU6TGFiZWwxMjUwMjA3Mjg3",
                    "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2019-02-26T20:47:59Z",
            "updated_at": "2019-02-26T22:59:24Z",
            "closed_at": "2019-02-26T20:57:04Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/3",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/3",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/3.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/3.patch"
            },
            "body": "Adds the following:\r\n\r\n- Renames project to coolwip \r\n- Adds mocks for testing without Github\r\n- Adds a settings page to get connected to Github (not yet tied into services)\r\n- Adds coverage reporting to Codecov\r\n- Adds publishing to npm.js\r\n- Builds in CirceCI\r\n- Adds semantic release",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/2",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/2/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/2/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/2/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/2",
            "id": 395054012,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MjQxNjE2MDY5",
            "number": 2,
            "title": "Test PR #2 - Team Mention",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [

            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2019-01-01T04:13:33Z",
            "updated_at": "2020-02-19T01:51:51Z",
            "closed_at": "2020-02-19T01:51:51Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/2",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/2",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/2.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/2.patch"
            },
            "body": "@LeanAgileSoftware/test ",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/1",
            "repository_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip",
            "labels_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/1/labels{/name}",
            "comments_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/1/comments",
            "events_url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/issues/1/events",
            "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/1",
            "id": 395053354,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MjQxNjE1Njg0",
            "number": 1,
            "title": "Test PR #1 - Team Mention",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [

            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 0,
            "created_at": "2019-01-01T03:53:00Z",
            "updated_at": "2020-03-04T01:34:36Z",
            "closed_at": "2020-03-04T01:34:36Z",
            "author_association": "MEMBER",
            "pull_request": {
                "url": "https://api.github.com/repos/LeanAgileSoftware/coolwip/pulls/1",
                "html_url": "https://github.com/LeanAgileSoftware/coolwip/pull/1",
                "diff_url": "https://github.com/LeanAgileSoftware/coolwip/pull/1.diff",
                "patch_url": "https://github.com/LeanAgileSoftware/coolwip/pull/1.patch"
            },
            "body": "@LeanAgileSoftware/test ",
            "score": 1.0
        },
        {
            "url": "https://api.github.com/repos/octokit/rest.js/issues/1177",
            "repository_url": "https://api.github.com/repos/octokit/rest.js",
            "labels_url": "https://api.github.com/repos/octokit/rest.js/issues/1177/labels{/name}",
            "comments_url": "https://api.github.com/repos/octokit/rest.js/issues/1177/comments",
            "events_url": "https://api.github.com/repos/octokit/rest.js/issues/1177/events",
            "html_url": "https://github.com/octokit/rest.js/pull/1177",
            "id": 394921988,
            "node_id": "MDExOlB1bGxSZXF1ZXN0MjQxNTIxNTE2",
            "number": 1177,
            "title": "docs(README): typo",
            "user": {
                "login": "chodges15",
                "id": 24880218,
                "node_id": "MDQ6VXNlcjI0ODgwMjE4",
                "avatar_url": "https://avatars0.githubusercontent.com/u/24880218?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/chodges15",
                "html_url": "https://github.com/chodges15",
                "followers_url": "https://api.github.com/users/chodges15/followers",
                "following_url": "https://api.github.com/users/chodges15/following{/other_user}",
                "gists_url": "https://api.github.com/users/chodges15/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/chodges15/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/chodges15/subscriptions",
                "organizations_url": "https://api.github.com/users/chodges15/orgs",
                "repos_url": "https://api.github.com/users/chodges15/repos",
                "events_url": "https://api.github.com/users/chodges15/events{/privacy}",
                "received_events_url": "https://api.github.com/users/chodges15/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1094972106,
                    "node_id": "MDU6TGFiZWwxMDk0OTcyMTA2",
                    "url": "https://api.github.com/repos/octokit/rest.js/labels/released",
                    "name": "released",
                    "color": "ededed",
                    "default": false,
                    "description": null
                }
            ],
            "state": "closed",
            "locked": false,
            "assignee": null,
            "assignees": [

            ],
            "milestone": null,
            "comments": 1,
            "created_at": "2018-12-31T02:55:15Z",
            "updated_at": "2019-01-03T02:21:11Z",
            "closed_at": "2019-01-01T18:08:42Z",
            "author_association": "CONTRIBUTOR",
            "pull_request": {
                "url": "https://api.github.com/repos/octokit/rest.js/pulls/1177",
                "html_url": "https://github.com/octokit/rest.js/pull/1177",
                "diff_url": "https://github.com/octokit/rest.js/pull/1177.diff",
                "patch_url": "https://github.com/octokit/rest.js/pull/1177.patch"
            },
            "body": "Fix typo in automatic retries example.\r\n",
            "score": 1.0
        }
    ]
}
